name = "as-mcp-platform-aerostackmcp-google-docs-production"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "as-mcp-platform-aerostackmcp-google-docs-production"
